#automatically generated by the clientobjectgenerator
from clientproxy import *

class Bank():
	def __init__(self):
		invoke_command(self, "__init__")

	def __str__(self):
		invoke_command(self, "__str__")

	def balance(self, args):
		invoke_command(self, "balance", args)

	def close(self, args):
		invoke_command(self, "close", args)

	def debit(self, args):
		invoke_command(self, "debit", args)

	def deposit(self, args):
		invoke_command(self, "deposit", args)

	def open(self, args):
		invoke_command(self, "open", args)

