#automatically generated by the clientobjectgenerator
from clientproxy import *

class Barrier():
	def __init__(self):
		invoke_command(self, "__init__")

	def __str__(self):
		invoke_command(self, "__str__")

	def create(self, args):
		invoke_command(self, "create", args)

	def wait(self, args):
		invoke_command(self, "wait", args)

