#automatically generated by the clientobjectgenerator
from clientproxy import *

class History():
	def __init__(self):
		invoke_command(self, "__init__")

	def __str__(self):
		invoke_command(self, "__str__")

	def append(self, args):
		invoke_command(self, "append", args)

	def read(self, args):
		invoke_command(self, "read", args)

	def write(self, args):
		invoke_command(self, "write", args)

