#automatically generated by the clientobjectgenerator
from clientproxy import *

class Lock():
	def __init__(self):
		invoke_command(self, "__init__")

	def __str__(self):
		invoke_command(self, "__str__")

	def acquire(self, args, _paxi_designated, _paxi_client_cmdno, _paxi_me):
		invoke_command(self, "acquire", args, _paxi_designated, _paxi_client_cmdno, _paxi_me)

	def release(self, args, _paxi_designated, _paxi_client_cmdno, _paxi_me):
		invoke_command(self, "release", args, _paxi_designated, _paxi_client_cmdno, _paxi_me)

