#automatically generated by the clientobjectgenerator
from clientproxy import *

class Membership():
	def __init__(self):
		invoke_command(self, "__init__")

	def __str__(self):
		invoke_command(self, "__str__")

	def add(self, args, _paxi_designated, _paxi_client_cmdno, _paxi_me):
		invoke_command(self, "add", args, _paxi_designated, _paxi_client_cmdno, _paxi_me)

	def remove(self, args, _paxi_designated, _paxi_client_cmdno, _paxi_me):
		invoke_command(self, "remove", args, _paxi_designated, _paxi_client_cmdno, _paxi_me)

