#automatically generated by the clientobjectgenerator
from clientproxy import *

class Membership():
	def __init__(self):
		invoke_command(self, "__init__")

	def __str__(self):
		invoke_command(self, "__str__")

	def add(self, args):
		invoke_command(self, "add", args)

	def remove(self, args):
		invoke_command(self, "remove", args)

