#automatically generated by the clientobjectgenerator
from clientproxy import *

class Rlock():
	def __init__(self):
		invoke_command(self, "__init__")

	def __str__(self):
		invoke_command(self, "__str__")

	def acquire(self, args):
		invoke_command(self, "acquire", args)

	def release(self, args):
		invoke_command(self, "release", args)

