#!/usr/bin/env python
'''
@author: Deniz Altinbuken, Emin Gun Sirer
@note: script to initialize concoord with given number of nodes
@date: February 1, 2011
@copyright: See COPYING.txt
'''
from concoord.openreplica.openreplicainitializer import *
from concoord.safetychecker import *
from concoord.proxygenerator import *
from concoord.serversideproxyast import *

def main():
    try:
        with open(options.objectfilepath, 'rU') as fd:
            clientcode = fd.read()
        # Check safety
        if not check_object(clientcode):
            print "Object is not safe for us to execute."
            os._exit(1)
        # Start Nodes
        print "Connecting to Planet Lab"
        configuration = (int(options.replicanum), int(options.acceptornum), int(options.nameservernum))
        start_nodes(options.subdomain, options.objectfilepath, options.classname, configuration)
        # Create Proxy
        print "Creating proxy..."
        clientproxycode = createclientproxy(clientcode, options.classname, None)
        clientproxycode = clientproxycode.replace('\n\n\n', '\n\n')
        print "Proxy Code:"
        print clientproxycode
    except Exception as e:
        parser.print_help()
    
if __name__=='__main__':
    main()
