#!/usr/bin/env python
'''
@author: Deniz Altinbuken, Emin Gun Sirer
@note: script to add node
@date: February 1, 2011
@copyright: See COPYING.txt
'''
from concoord.openreplica.openreplicaaddnode import *

def main():
    try:
        start_node(options.nodetype, options.subdomain, options.clientobjectfilepath,
                   options.classname, options.bootstrapname)
    except Exception as e:
        print "Error: ", e
    
if __name__=='__main__':
    main()
