#!/usr/bin/env python
'''
@author: Deniz Altinbuken, Emin Gun Sirer
@note: script for replica
@date: February 1, 2012
@copyright: See COPYING.txt
'''
import signal
from concoord.replica import *

def main():
    replicanode = Replica()
    replicanode.startservice()
    signal.signal(signal.SIGINT, replicanode.terminate_handler)
    signal.signal(signal.SIGTERM, replicanode.terminate_handler)
    signal.pause()
    
if __name__=='__main__':
    main()
