#automatically generated by the proxygenerator
from clientproxy import *

class Bank():
	def __init__(self):
		invoke_command(self, "__init__")

	def __str__(self):
		invoke_command(self, "__str__")

	def balance(self, accntno):
		invoke_command(self, "balance", accntno)

	def close(self, accntno):
		invoke_command(self, "close", accntno)

	def debit(self, accntno, amount):
		invoke_command(self, "debit", accntno, amount)

	def deposit(self, accntno, amount):
		invoke_command(self, "deposit", accntno, amount)

	def open(self, accntno):
		invoke_command(self, "open", accntno)

