#automatically generated by the proxygenerator
from clientproxy import *

class Foo():
	def __init__(self):
		invoke_command(self, "__init__")

	def getvalue(self):
		invoke_command(self, "getvalue")

	def setvalue(self, newval):
		invoke_command(self, "setvalue", newval)

