#automatically generated by the proxygenerator
from clientproxy import *

class OpenReplicaCoord():
	def __init__(self):
		ClientProxy()

	def __str__(self):
		invoke_command(self, "__str__")

	def addnodetosubdomain(self, subdomain, node):
		invoke_command(self, "addnodetosubdomain", subdomain, node)

	def addsubdomain(self, subdomain):
		invoke_command(self, "addsubdomain", subdomain)

	def delnodefromsubdomain(self, subdomain, node):
		invoke_command(self, "delnodefromsubdomain", subdomain, node)

	def delsubdomain(self, subdomain):
		invoke_command(self, "delsubdomain", subdomain)

	def getnodes(self, subdomain):
		invoke_command(self, "getnodes", subdomain)

	def getsubdomains(self):
		invoke_command(self, "getsubdomains")

