#automatically generated by the proxygenerator
from clientproxy import *

class OpenReplicaCoord():
	def __init__(self):
		invoke_command(self, "__init__")

	def addnodestosubdomain(self, subdomain, nodes):
		invoke_command(self, "addnodestosubdomain", subdomain, nodes)

	def addsubdomain(self, subdomain):
		invoke_command(self, "addsubdomain", subdomain)

	def delnodesfromsubdomain(self, subdomain, nodes):
		invoke_command(self, "delnodesfromsubdomain", subdomain, nodes)

	def delsubdomain(self, subdomain):
		invoke_command(self, "delsubdomain", subdomain)

	def getnodes(self, subdomain):
		invoke_command(self, "getnodes", subdomain)

	def getsubdomains(self):
		invoke_command(self, "getsubdomains")

