#automatically generated by the proxygenerator
from clientproxyonerun import *

class Bank():
    def __init__(self, bootstrap=213.73.40.105:6668):
        self.proxy = ClientProxy(bootstrap)
        self.proxy.invoke_command("__init__", self)

    def open(self, accntno, **kwargs):
        self.proxy.invoke_command("open", self, accntno)

    def close(self, accntno, **kwargs):
        self.proxy.invoke_command("close", self, accntno)

    def debit(self, accntno, amount, **kwargs):
        self.proxy.invoke_command("debit", self, accntno, amount)

    def deposit(self, accntno, amount, **kwargs):
        self.proxy.invoke_command("deposit", self, accntno, amount)

    def balance(self, accntno, **kwargs):
        self.proxy.invoke_command("balance", self, accntno)

    def __str__(self):
        self.proxy.invoke_command("__str__", self)

